### ISSUE TITLE
Mirai更新了新版本之后好像用不了。报错了

### ISSUE THREAD

**Issue by Oeeder** [Nana-Miko/GengSearch#1]
data Get Success
Listening……
Mirai未运行或未配置mah插件
错误详情:
Traceback (most recent call last):
  File "/home/oeeder/geng/GengSearch.py", line 233, in Listening
    message=simuse.Fetch_Message(data)
  File "/home/oeeder/geng/simuse.py", line 65, in Fetch_Message
    Message=res['data']
KeyError: 'data'

save log
sh: pause: command not found
Traceback (most recent call last):
  File "/home/oeeder/geng/GengSearch.py", line 385, in <module>
    main()
  File "/home/oeeder/geng/GengSearch.py", line 381, in main
    GengSearch(data,seting,plat)
  File "/home/oeeder/geng/GengSearch.py", line 305, in GengSearch
    SearchList=Listening(data,seting)
  File "/home/oeeder/geng/GengSearch.py", line 240, in Listening
    if type(message)==type(0):
UnboundLocalError: local variable 'message' referenced before assignment

**Comment by JHue58** [comment]
之前是一直在使用的嘛，试试把api-http退回到2.3.3？

**Comment by Oeeder** [comment]
之前是有在使用的，自从今天平台更新后就不行了，我试试退回一下版本

**Comment by JHue58** [comment]
有什么报错吗？

**Comment by Oeeder** [comment]
at net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invoke(Authorization.kt)
        at net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invoke(Authorization.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.intercept(HttpRouterAccessHandler.kt:36)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.access$intercept(HttpRouterAccessHandler.kt:25)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invokeSuspend(HttpRouterAccessHandler.kt:91)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invoke(HttpRouterAccessHandler.kt)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invoke(HttpRouterAccessHandler.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:127)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
        at io.ktor.server.cio.CIOApplicationEngine$handleRequest$2.invokeSuspend(CIOApplicationEngine.kt:196)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

这是Mirai上的报错

**Comment by Oeeder** [comment]
api也确认在正常运行了，我试一下回滚

**Comment by Oeeder** [comment]
问题解决了，不知道为什么我这MCL自动下载了一个很奇怪的版本的api-http。
我自己手动删除后安装了别的版本就解决了
